RedHatInsights/access-requests-frontend

src/Routes/AccessRequestDetailsPage.js

Add ouiaId's for the cards on the request details page

---

config/dev.webpack.config.js
package-lock.json
package.json
src/Routes/AccessRequestDetailsPage.js

fix baseUrl

---

package-lock.json
package.json
src/Components/AccessRequestsTable.js

jira: https://issues.redhat.com/browse/RHCLOUD-16218
- update filters flag on select value change

Fix filters empty state

---

src/Components/AccessRequestsTable.js

Should fix: https://issues.redhat.com/browse/RHCLOUD-17072

Reset page on filters change

---

src/Components/EditRequestModal.js

jira: https://issues.redhat.com/browse/RHCLOUD-18705
Just a note here. This "thing" has to refactor. Ideally using DDF. its not maintainable in this state.

Add org_id to access request POST payload.

---

src/Components/EditRequestModal.js

jira: https://issues.redhat.com/browse/RHCLOUD-18705

Rename org_id to target_org

---

package.json
src/Components/AccessRequestsTable.js
src/Routes/AccessRequestDetailsPage.js

Changing query parameters from 'user_id' to 'target_account'
Also wrapping it around conditionals depending on whether isInternal or not.

Api request change

---

src/Components/EditRequestModal.js

jira: https://issues.redhat.com/browse/RHCLOUD-19372
- fix query when requesting access request for editing
- disable org id input while editing the request

Disable edit orig

---

package-lock.json
package.json
src/Components/AccessRequestsTable.js

-Upgrade frontend components config

Fix wrong reference in the api request

---

package-lock.json
package.json

Upgrade fec-config

---

fec.config.js
src/Components/AccessRequestsTable.js
src/Routes.js

possible fix for: https://issues.redhat.com/browse/RHCLOUD-20901

Start UI rendering after user object is ready.

---

fec.config.js
package-lock.json
package.json
src/Components/access-requests-wizard/AccessDuration.js

jira: https://issues.redhat.com/browse/RHCLOUD-25786, https://issues.redhat.com/browse/RHCLOUD-25787
Cause of the issue: undocumented minor release breaking change in PF date picker component: https://github.com/patternfly/patternfly-react/commit/a863bf58ab92f97cc729010b6fce963ffe7d37f1#diff-68d3d99131e6cc3880beab4e34d4a77bdc6fac4e92c061ae7097bc7752ee047b
- fix date picker onChange callback argument order
- fix access duration tooltip text

Fix access duration date pickers values

---

build_deploy.sh

Adding an if-statement to `build_deploy.sh` to properly tag the Container Image generated when building from the Security-Compliance Branch. 
```
if [[ "$GIT_BRANCH" == "origin/security-compliance" ]]; then
export IMAGE_TAG="sc-$(date +%Y%m%d)-$(git rev-parse --short=7 HEAD)"
fi
```
---
---
##
##

Adding SC Build Support to Build Deploy Script

---

src/Components/mua-roles-table/MUARolesTable.js

- Make Role Name filter case-insensitive
- Make Role Name filter by `display_name` instead of `name`
[RHCLOUD-35149](https://issues.redhat.com/browse/RHCLOUD-35149)
---
---
##
##

Fix Role Name filter

---

README.md

description text...
[RHCLOUDXXXX](https://issues.redhat.com/browse/RHCLOUDXXXX)
---
---
##
##

Trigger manual release

---

README.md

description text...
[RHCLOUDXXXX](https://issues.redhat.com/browse/RHCLOUDXXXX)
---
---
##
##

Trigger manual release for Konflux image

---

src/Components/AccessRequestsTable.js
src/Components/access-requests-wizard/ReviewDetails.js
src/Components/access-requests-wizard/schema.js

- Add `Account name` to Review details and Access Requests table
- Fix missing/incorrect columns.
[RHCLOUD-35348](https://issues.redhat.com/browse/RHCLOUD-35348)
---
---
##
##

Add Account Name to the overview of Access Requests and their Request details

---

.gitmodules
.tekton/access-requests-frontend-pull-request.yaml
.tekton/access-requests-frontend-push.yaml

For [RHCLOUD-37969](https://issues.redhat.com/browse/RHCLOUD-37969)

Update to use new build-tools

---

.gitignore
.storybook/README.md
.storybook/main.ts
.storybook/preview.ts
CURSOR-CONTEXT.md
CURSOR-PROMPTS.md
package-lock.json
package.json
src/Components/access-requests-wizard/AccessDuration.js
src/Components/access-requests-wizard/AccessDuration.stories.tsx

[RHCLOUD-31622](https://issues.redhat.com/browse/RHCLOUD-31622)
It's difficult to test some sections and features of this app in stage/production without the proper access levels. This PR tests and fixes the problem highlighted in the ticket above by testing the calendar component in a Storybook sandbox.
---
---
##
##

Rhcloud 31622

---

.github/workflows/chromatic.yml
CHROMATIC_SETUP.md

This PR should automatically build Storybook for the master branch and for all PRs from the Experience UI Commiteers
---
---
##
##

feat: automatically publish Storybook stories on Chromatic for approved contributors

---

.tekton/access-requests-frontend-sc-pull-request.yaml
.tekton/access-requests-frontend-sc-push.yaml

Adopting shared remote pipeline configuration for SC .tekton files and adding those to main.
(https://issues.redhat.com/browse/HCMSEC-999)
---

Add sc tekton files
